[package]
name = "mpv-client-cross"
version = "1.2.4"
edition.workspace = true
authors.workspace = true
description = "Bindings for libmpv client API that allow you to create plugins for MPV in Rust"
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
# Include nothing by default
default = []
bindgen = ["ffi/bindgen"]
macros = ["mpv-client-macros"]

[dependencies]
ffi.workspace = true
mpv-client-macros = { workspace = true, optional = true }
libc.workspace = true
serde.workspace = true
log.workspace = true

[lints]
workspace = true
