[package]
name = "mpv-client-cross-macros"
description = "Proc macros for mpv client bindings"
keywords = ["mpv", "libmpv", "macros", "proc-macro"]
categories = ["api-bindings"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
